CREATE TABLE my_client (
  id SERIAL PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  slug VARCHAR(100) NOT NULL UNIQUE,
  is_project VARCHAR(30) CHECK (is_project IN ('0', '1')) NOT NULL DEFAULT '0',
  self_capture CHAR(1) NOT NULL DEFAULT '1',
  client_prefix CHAR(4) NOT NULL,
  client_logo VARCHAR(255) NOT NULL DEFAULT 'no-image.jpg',
  address TEXT DEFAULT NULL,
  phone_number VARCHAR(50) DEFAULT NULL,
  city VARCHAR(50) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL
);
